local cmod = require("assets/scripts/Counter")
local c = cmod(0)
c:add(4)
c:decrement()
io.write("val=" .. c:getVal())
io.write("\n")
c:subtract(-2)
c:increment()
io.write(c:toString())
return io.write("\n")
